user_education_choices = [
    ("bachelor", "Licencjat"),
    ("engineer", "Inżynier"),
    ("master", "Magister"),
    ("phd", "Doktor"),
    ("unspecified", "Nie chcę podawać"),
]

user_notice_period_choices = [
    ("immediately", "Od zaraz"),
    ("month", "1 miesiąc"),
    ("three_months", "3 miesiące"),
    ("more_months", "3+ miesiące"),
]

user_work_model_choices = [
    ("remotely", "Zdalnie"),
    ("hybrid", "Hybrydowo"),
    ("stationary", "Stacjonarnie"),
]

user_relocation_choices = [
    ("yes", "Tak"),
    ("no", "Nie"),
]

user_relocation_cities_choices = [
    ("Miasta", (
        ("warsaw", "Warszawa"),
        ("krakow", "Kraków"),
        ("lodz", "Łódź"),
        ("wroclaw", "Wrocław"),
        ("poznan", "Poznań"),
        ("gdansk", "Gdańsk"),
        ("gdynia", "Gdynia"),
        ("sopot", "Sopot"),
        ("szczecin", "Szczecin"),
        ("bydgoszcz", "Bydgoszcz"),
        ("lublin", "Lublin"),
        ("bialystok", "Białystok"),
        ("katowice", "Katowice"),
        ("gorzow-wielkopolski", "Gorzów Wielkopolski"),
        ("rzeszow", "Rzeszów"),
        ("opole", "Opole"),
        ("krosno", "Krosno"),
        ("torun", "Toruń"),
        ("olsztyn", "Olsztyn"),
        ("kielce", "Kielce"),
    )),
]

user_work_contract_choices = [
    ("contract", "UoP"),
    ("commission", "UZ"),
    ("b2b", "B2B"),
    ("internship", "Staż"),
]

user_contact_choices = [
    ("phone", "Telefon"),
    ("email", "Email"),
    ("chat", "Czat"),
]

user_languages_choices = [
    ("Języki", (
        ("english", "Angielski"),
        ("spanish", "Hiszpański"),
        ("french", "Francuski"),
        ("german", "Niemiecki"),
        ("italian", "Włoski"),
        ("portuguese", "Portugalski"),
        ("russian", "Rosyjski"),
        ("dutch", "Holenderski"),
        ("swedish", "Szwedzki"),
        ("polish", "Polski"),
        ("chinese", "Chiński"),
        ("japanese", "Japoński"),
        ("arabic", "Arabski"),
        ("hindi", "Hinduski"),
        ("bengali", "Bengalski"),
        ("korean", "Koreański"),
        ("turkish", "Turecki"),
        ("vietnamese", "Wietnamski"),
        ("greek", "Grecki"),
        ("hungarian", "Węgierski"),
        ("czech", "Czeski"),
        ("swahili", "Suahili"),
    )),
]

user_skills_choices = [
    ("Język programowania", (
        ("javascript", "JavaScript"),
        ("python", "Python"),
        ("java", "Java"),
        ("csharp", "C#"),
        ("c++", "C++"),
        ("typescript", "Typescript"),
        ("php", "PHP"),
        ("swift", "Swift"),
        ("ruby", "Ruby"),
        ("go", "Go"),
        ("kotlin", "Kotlin"),
        ("objective_c", "Objective-C"),
        ("r", "R"),
        ("matlab", "Matlab"),
        ("bash", "Bash"),
        ("rust", "Rust"),
        ("dart", "Dart"),
        ("scala", "Scala"),
        ("groovy", "Groovy"),
        ("perl", "Perl"),
        ("html", "HTML"),
        ("css", "CSS"),
        ("sql", "SQL"),
        ("lua", "Lua"),
        ("visual_basic", "Visual Basic"),
        ("assembler", "Assembler"),
        ("haskel", "Haskel"),
        ("julia", "Julia"),
        ("erland", "Erlang"),
        ("cobol", "Cobol"),
        ("c", "C"),
    )),
    ("Frameworki i biblioteki", (
        ("django", "Django"),
        ("react", "React"),
        ("angular", "Angular"),
        ("spring", "Spring Framework"),
        ("flask", "Flask"),
        ("vue", "Vue.js"),
        ("laravel", "Laravel"),
        ("express", "Express.js"),
        ("rails", "Ruby on Rails"),
        ("tensorflow", "TensorFlow"),
        ("pytorch", "PyTorch"),
        ("bootstrap", "Bootstrap"),
        ("jquery", "jQuery"),
        ("flutter", "Flutter"),
        ("react_native", "React Native"),
        ("django_rest", "Django REST framework"),
        ("laravel_livewire", "Laravel Livewire"),
        ("flask_restful", "Flask-RESTful"),
        ("spring_boot", "Spring Boot"),
        ("rxjs", "RxJS"),
        ("fastapi", "FastAPI"),
        ("graphql", "GraphQL"),
        ("ionic", "Ionic"),
        ("express_graphql", "Express GraphQL"),
        ("koa", "Koa"),
        ("redux", "Redux"),
        ("mobx", "MobX"),
        ("numpy", "NumPy"),
        ("pandas", "Pandas"),
        ("scikit_learn", "scikit-learn"),
    )),
    ("Narzędzia", (
        ("azure", "Azure"),
        ("aws", "AWS"),
        ("docker", "Docker"),
        ("kubernetes", "Kubernetes"),
        ("jenkins", "Jenkins"),
        ("git", "Git"),
        ("vs_code", "VS Code"),
        ("ansible", "Ansible"),
        ("terraform", "Terraform"),
        ("postman", "Postman"),
        ("prometheus", "Prometheus"),
        ("grafana", "Grafana"),
        ("nginx", "NGINX"),
        ("elastic_search", "Elasticsearch"),
        ("kibana", "Kibana"),
        ("splunk", "Splunk"),
        ("wireshark", "Wireshark"),
        ("postgreSQL", "PostgreSQL"),
        ("mongoDB", "MongoDB"),
        ("jenkins", "Jenkins"),
        ("confluence", "Confluence"),
        ("slack", "Slack"),
        ("ansible_tower", "Ansible Tower"),
        ("wireshark", "Wireshark"),
        ("virtualbox", "VirtualBox"),
        ("vagrant", "Vagrant"),
        ("prometheus", "Prometheus"),
        ("docker_compose", "Docker Compose"),
    )),
    ("Metodyka pracy", (
        ("agile", "Agile"),
        ("scrum", "Scrum"),
        ("kanban", "Kanban"),
        ("devops", "DevOps"),
        ("waterfall", "Waterfall"),
        ("lean", "Lean"),
        ("fdd", "FDD"),
        ("pair_programming", "Pair Programming"),
        ("tdd", "TDD"),
        ("ci", "CI"),
        ("cd", "CD"),
        ("spiral", "Spiral Model"),
        ("rad", "RAD"),
        ("iterative_model", "Iterative Model"),
        ("big_bang", "Big Bang Model"),
        ("feature_toggle", "Feature Toggle"),
        ("mob_programming", "Mob Programming"),
        ("eda", "EDA"),
        ("microservices", "Microservices"),
        ("sprint_review", "Sprint Review"),
        ("pair_design", "Pair Design"),
        ("mdd", "MDD"),
        ("spike", "Spike"),
        ("rapid_prototyping", "Rapid Prototyping"),
        ("continuous_testing", "Continuous Testing"),
        ("safe", "SAFe"),
        ("feature_flow", "Feature Flow"),
    )),
    ("Systemy zarządzania", (
        ("asana", "Asana"),
        ("jira", "Jira"),
        ("trello", "Trello"),
        ("bitbucket", "Bitbucket"),
        ("github", "GitHub"),
        ("gitlab", "GitLab"),
        ("redmine", "Redmine"),
        ("clickup", "ClickUp"),
        ("wrike", "Wrike"),
        ("notion", "Notion"),
        ("basecamp", "Basecamp"),
        ("azure_devops", "Azure DevOps"),
        ("clubhouse", "Clubhouse"),
        ("targetprocess", "Targetprocess"),
        ("monday", "Monday.com"),
    )),
]
