# Generated by Django 4.2.4 on 2023-08-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_position', models.CharField(blank=True, max_length=200, null=True)),
                ('job_start_date', models.DateTimeField(blank=True, null=True)),
                ('company_size', models.IntegerField(blank=True, null=True)),
                ('suggested_salary', models.IntegerField(blank=True, null=True)),
                ('upload_resume', models.FileField(blank=True, null=True, upload_to='resume')),
                ('announcement_content', models.CharField(blank=True, max_length=2000, null=True)),
                ('redirect_link', models.URLField(blank=True, db_index=True, unique=True)),
                ('is_remote', models.BooleanField()),
                ('is_hybrid', models.BooleanField()),
                ('is_promoted', models.BooleanField()),
            ],
        ),
    ]
