# Generated by Django 4.2.4 on 2023-08-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_workoffer_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoffer',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoffer',
            name='job_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
