# Generated by Django 4.2.4 on 2023-08-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jobannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoffer',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
